server:
  port: 8080
wechat:
  # sgj.proxy.jingxiantech.com:  改成自己的域名，还有static/preorder.html里面102,108行
  notifyurl: http://sgj.proxy.jingxiantech.com/pay/paidNotify
pooul:
  pay:
    url: https://api-uat.pooul.com/v2/pay?merchant_id={0}
    preOrder: https://api-uat.pooul.com/v2/pay/pre_order?merchant_id={0}
    login: https://api-uat.pooul.com/web/user/session/login_name
    create: https://api-uat.pooul.com/cms/merchants
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml